# Generated by Django 5.2.3 on 2025-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_is_paid_payment_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
