# Generated by Django 5.2.3 on 2025-06-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("transfer", "Transfer")], max_length=8
            ),
        ),
    ]
