# Generated by Django 5.2.3 on 2025-06-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_delete_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
