# Generated by Django 5.2.3 on 2025-06-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_rename_name_course_title_remove_lesson_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/previews/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lessons/previews/"
            ),
        ),
    ]
